import { ConfigTrama } from "../../interface/ConfigTrama";

export const configDate: ConfigTrama = {
  nombre: "date",
  alineacion_defecto: "derecha",
  columnas: [
    { longitud: 39 },
    { longitud: 10 },
    { longitud: 21 },
    { longitud: 22 },
    { longitud: 3 },
    { longitud: 22 },
    { longitud: 24 },
    { longitud: 6 },
    { longitud: 31 },
    { longitud: 10 },
    { longitud: 18 },
    { longitud: 34 },
    { longitud: 14 },
    { longitud: 12 },
    { longitud: 12 },
    { longitud: 12 },
    { longitud: 12 },
    { longitud: 12 },
    { longitud: 12 },
    { longitud: 12 },
    { longitud: 12 },
    { longitud: 12 },
    { longitud: 12 },
    { longitud: 12 },
    { longitud: 12 },
    { longitud: 12 },
  ],
};
